### ISSUE TITLE
nan values for magnetometer on zed2

### ISSUE THREAD

**Issue by ladrians** [stereolabs/zed-ros2-wrapper#107]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

We were using without any trouble the zed2, now we get trouble with the IMU MAG, specifically the magnetometer details

```
header: 
  seq: 29907
  stamp: 
    secs: 1664573644
    nsecs: 761844325
  frame_id: "zed_mag_link"
magnetic_field: 
  x: nan
  y: nan
  z: nan
magnetic_field_covariance: [3.9e-08, 0.0, 0.0, 0.0, 3.7e-08, 0.0, 0.0, 0.0, 4.7e-08]
```

We need the raw value to use the madgwick IMU filter to get an absolute value for outdoor navigation.

### Steps to Reproduce

1. Attached a svo simple file to reproduce the case.
2. Using ROS melodic

[zed01.zip](https://github.com/stereolabs/zed-ros2-wrapper/files/9687781/zed01.zip)

### Expected Result

The camera was working fine; from one day to the next week we detected this problem as the outdoor navigation got crazy.

### Actual Result

Weird values on IMU and Magnetometer.

### ZED Camera model

ZED2

### Environment

```shell
OS: Ubuntu 18.04.6 LTS
GPU: Nvidia Jetxon Xavier NX and Jetson Nano
Zed SDK: 3.7 and 3.2.1
ROS Melodic
```
